#!/bin/bash

#get the list of the files in the directory mentioned in the argument
fileList=$(find $1 -maxdepth 1 -type f -name ".*" | sort -u)
fileList=$fileList$'\n'$(find $1 -maxdepth 1 -type f ! -name ".*" | sort -u)

test=""

#iterate through each file in the list
while read file;
do

    #compare it to each of the other files in the list
    while read otherFile
    do

	#if the files have the same name, skip
	if [ "$file" != "$otherFile" ] 
	then
	    #compare the two files to see if their content is the same
	    test=$(comm -3 <(sort "$file") <(sort "$otherFile"))
	    if [ "$test" = "" ]
	    then
		#create a hardlink if files are same

		rm "$otherFile"
		ln "$file" "$otherFile"
	     fi
	fi
    done < <(echo -e "$fileList")

done < <(echo -e "$fileList")



